// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 2.2.0; do not edit! //
// ---------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------------- //
// pio_spi_cpha1 //
// ------------- //

#define pio_spi_cpha1_wrap_target 0
#define pio_spi_cpha1_wrap 2
#define pio_spi_cpha1_pio_version 1

static const uint16_t pio_spi_cpha1_program_instructions[] = {
            //     .wrap_target
    0x6001, //  0: out    pins, 1         side 0
    0x5001, //  1: in     pins, 1         side 1
    0xa042, //  2: nop                    side 0
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program pio_spi_cpha1_program = {
    .instructions = pio_spi_cpha1_program_instructions,
    .length = 3,
    .origin = -1,
    .pio_version = pio_spi_cpha1_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config pio_spi_cpha1_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + pio_spi_cpha1_wrap_target, offset + pio_spi_cpha1_wrap);
    sm_config_set_sideset(&c, 1, false, false);
    return c;
}

#include "hardware/gpio.h"
static inline void pio_spi_cpha1_program_init(PIO pio, uint sm, uint offset,
                                               uint mosi_pin, uint miso_pin,
                                               uint sck_pin, float clkdiv) {
    pio_sm_config c = pio_spi_cpha1_program_get_default_config(offset);
    sm_config_set_out_pins(&c, mosi_pin, 1);
    sm_config_set_in_pins(&c, miso_pin);
    sm_config_set_sideset_pins(&c, sck_pin);
    /* MSB first, autopull at 8 bits, autopush at 8 bits */
    sm_config_set_out_shift(&c, false, true, 8);
    sm_config_set_in_shift(&c, false, true, 8);
    sm_config_set_clkdiv(&c, clkdiv);
    /* Assign MOSI and SCK to PIO function.
     * MISO is left as SIO/GPIO input — PIO `in pins` reads the pad
     * state directly regardless of function mux, and setting GP16 to
     * PIO2 function (funcsel 8) may prevent the pad input from
     * reaching the PIO on RP2350. */
    pio_gpio_init(pio, mosi_pin);
    gpio_init(miso_pin);
    gpio_set_dir(miso_pin, GPIO_IN);
    pio_gpio_init(pio, sck_pin);
    /* Pin directions: MOSI and SCK = output, MISO = input */
    pio_sm_set_pindirs_with_mask(pio, sm,
        (1u << mosi_pin) | (1u << sck_pin),
        (1u << mosi_pin) | (1u << miso_pin) | (1u << sck_pin));
    /* SCK starts LOW */
    pio_sm_set_pins_with_mask(pio, sm, 0, 1u << sck_pin);
    pio_sm_init(pio, sm, offset, &c);
    pio_sm_set_enabled(pio, sm, true);
}

#endif

